# Generated by Django 4.0.5 on 2022-06-06 11:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='project_name', unique=True),
        ),
    ]
