# Generated by Django 4.0.3 on 2022-06-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_title_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_shot_des',
            new_name='project_shot_des_in_100_word',
        ),
    ]
