# Generated by Django 4.0.3 on 2022-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_project_shot_des_project_project_shot_des_in_100_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_shot_des_in_100_word',
            field=models.TextField(max_length=100),
        ),
    ]
