# Generated by Django 4.0.3 on 2022-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_url_project_url_do_not_use_http'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=30)),
                ('catagory_id', models.CharField(max_length=30)),
            ],
        ),
    ]
