# Generated by Django 4.0.5 on 2022-06-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.TextField(default='no'),
        ),
    ]
