# Generated by Django 4.0.3 on 2022-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clint_compny_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comapany_logo', models.ImageField(height_field=80, upload_to='brands/', width_field=272)),
            ],
        ),
    ]
