# Generated by Django 4.0.5 on 2022-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(upload_to='doc/')),
                ('Experinace', models.IntegerField(max_length=2)),
                ('skill', models.CharField(max_length=50)),
                ('job_profile', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
