# Generated by Django 4.0.5 on 2022-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerregister',
            name='Experinace',
            field=models.CharField(max_length=2),
        ),
    ]
