# Generated by Django 4.0.5 on 2022-06-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_careerregister_experinace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerregister',
            name='document',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
